services:
  app:
    image: ${ORG_NAME}/${APP_SLUG}:${APP_VERSION}-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=${BASE_IMAGE}
        - TZ=${TZ}
        - APP_PORT=${APP_PORT}
      target: development
    ports:
      - "${APP_FORWARD_PORT}:${APP_PORT}" 
    entrypoint: /entrypoint.sh
    volumes:
      - ./:/app
      - ./entrypoint.sh:/entrypoint.sh
